# Generated by Django 5.0.14 on 2026-01-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('set', models.CharField(max_length=100)),
                ('oracle_text', models.TextField()),
                ('mana_value', models.SmallIntegerField()),
                ('power', models.SmallIntegerField()),
                ('toughness', models.SmallIntegerField()),
                ('rarity', models.SmallIntegerField()),
                ('set_abbreviation', models.CharField(max_length=3)),
                ('commander_legality', models.CharField(choices=[('LG', 'Legal'), ('NL', 'Nonlegal')], default='LG', max_length=2)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='mtg_card_name_13c72f_idx')],
            },
        ),
    ]
