# Generated by Django 5.0.14 on 2026-01-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(max_length=1),
        ),
    ]
