# Generated by Django 5.0.14 on 2026-01-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0002_alter_card_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(default='card', max_length=250),
            preserve_default=False,
        ),
    ]
