# Generated by Django 5.0.14 on 2026-02-12 02:14

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0005_card_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
