# Generated by Django 6.0.2 on 2026-03-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
