# Generated by Django 6.0.2 on 2026-03-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0009_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='added_cards', to='mtg.card'),
        ),
    ]
